name: master-workflow

on:
  push:
    branches:
      - master

jobs:
  semver:
    name: semantic version tagging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup/install go
        uses: actions/setup-go@v2
          with:
            go-version: '^1.13.1'
      - name: install semver package
        run: github.com/stevenmatthewt/semantics
      - name: run semver incrementer
        run: |
          echo "Incrementing semantic version and tagging master branch"
